cp nb-bows/2-bins/predicting_split-5-of-5.png acc/nb-bows-2-bins.png
cp nb-bows/3-bins/predicting_split-3-of-5.png acc/nb-bows-3-bins.png
cp nb-bows/4-bins/predicting_split-4-of-5.png acc/nb-bows-4-bins.png
cp nb-bigrams/2-bins/predicting_split-5-of-5.png acc/nb-bigrams-2-bins.png
cp nb-bigrams/3-bins/predicting_split-5-of-5.png acc/nb-bigrams-3-bins.png
cp nb-bigrams/4-bins/predicting_split-2-of-5.png acc/nb-bigrams-4-bins.png
cp nb-tfidf/2-bins/predicting_split-4-of-5.png acc/nb-tfidf-2-bins.png
cp nb-tfidf/3-bins/predicting_split-5-of-5.png acc/nb-tfidf-3-bins.png
cp nb-tfidf/4-bins/predicting_split-2-of-5.png acc/nb-tfidf-4-bins.png
cp nb-other/2-bins/predicting_split-1-of-5.png acc/nb-other-2-bins.png
cp nb-other/3-bins/predicting_split-2-of-5.png acc/nb-other-3-bins.png
cp nb-other/4-bins/predicting_split-2-of-5.png acc/nb-other-4-bins.png
cp svm-bows/2-bins/predicting_split-3-of-5.png acc/svm-bows-2-bins.png
cp svm-bows/3-bins/predicting_split-3-of-5.png acc/svm-bows-3-bins.png
cp svm-bows/4-bins/predicting_split-4-of-5.png acc/svm-bows-4-bins.png
cp svm-bigrams/2-bins/predicting_split-3-of-5.png acc/svm-bigrams-2-bins.png
cp svm-bigrams/3-bins/predicting_split-3-of-5.png acc/svm-bigrams-3-bins.png
cp svm-bigrams/4-bins/predicting_split-2-of-5.png acc/svm-bigrams-4-bins.png
cp svm-tfidf/2-bins/predicting_split-4-of-5.png acc/svm-tfidf-2-bins.png
cp svm-tfidf/3-bins/predicting_split-3-of-5.png acc/svm-tfidf-3-bins.png
cp svm-tfidf/4-bins/predicting_split-3-of-5.png acc/svm-tfidf-4-bins.png
cp svm-other/2-bins/predicting_split-5-of-5.png acc/svm-other-2-bins.png
cp svm-other/3-bins/predicting_split-5-of-5.png acc/svm-other-3-bins.png
cp svm-other/4-bins/predicting_split-5-of-5.png acc/svm-other-4-bins.png
